### ISSUE TITLE
Can't find latest release on sonatype

### ISSUE THREAD

**Issue by daksh7011** [HyacinthBots/doc-generator#16]
Good day, 

I cannot find the `0.1.4` release on `https://oss.sonatype.org/content/repositories/snapshots` or on Maven Central.

Gradle kept complaining that it cannot find the dependency anywhere: `Could not resolve org.hyacinthbots:doc-generator:0.1.4.`

To further investigate, I tried `0.1.1` and it worked. However, it requires old kordex version, so I cannot use it.

Please let me know if I am doing something wrong here.

**Comment by NoComment1105** [comment]
Hi, thanks for opening an issue! I don't believe I've made any releases recently, so if you make use of the snapshot repository and then use version `0.2.2-SNAPSHOT` and all should be well. Please not doc gen does not work with KordEx 2.3.0 currently

**Comment by daksh7011** [comment]
Thank you for your swift reply. I can resolve `0.2.2-SNAPSHOT`. 😄 

Closing this issue.
